[package]
name = "indigo-cli"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
diff = { workspace = true }
indigo-core = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
